create database triggers;
use triggers;

create table users
(
    username varchar(100) not null primary key,
    age      decimal(3, 0)
);

# change delimiter from ; to $$
delimiter $$
create trigger must_be_adult
    # trigger time, trigger event and trigger table
    before insert
    on users
    for each row
begin
    if NEW.age < 18
        # NEW refers to data about to be entered
    then
        signal sqlstate '45000' set message_text = 'must be an adult';
        # 45000 -> a generic state representing unhandled user defined exception
        # generated by developer not the database itself
    end if;
end;
$$
delimiter ;
# change it back to ;
# this is to make sql not confuse the meta query as different real queries

# ----------------------------------------------------------------------------------------------------------------

use instagram;

delimiter $$
create trigger prevent_self_follows
    before insert
    on follows
    for each row
begin
    if NEW.follower_id = NEW.followee_id then
        signal sqlstate '45000' set message_text = 'self follows not allowed';
    end if;
end;
$$
delimiter ;

create table unfollows
(
    follower_id int not null,
    followee_id int not null,
    created_at  timestamp default now(),
    foreign key (followee_id) references users (id),
    foreign key (follower_id) references users (id),
    primary key (follower_id, followee_id)
);

# once a user is deleted from follows, immediately log him in unfollows table
delimiter $$
create trigger capture_unfollow
    after delete
    on follows
    for each row
begin
    #     insert into unfollows(follower_id, followee_id) value (OLD.follower_id, OLD.followee_id);
    insert into unfollows set follower_id = OLD.follower_id, followee_id = OLD.followee_id;
    # both are same 2nd uses some new syntax
end;
$$
delimiter ;

delete
from follows
where follower_id = 4;

# the moment I delete from follows table, the unfollows table gets populated
select *
from unfollows;

# ----------------------------------------------------------------------------------------------------------------

# managing triggers
show triggers;

drop trigger capture_unfollow;

# triggers can make debugging hard
# especially when triggers are chained together